CREATE TABLE tickets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200)             NOT NULL,
    description VARCHAR(5000)            NOT NULL,
    status      VARCHAR(30)               NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE  NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE  NOT NULL,
    CONSTRAINT chk_tickets_status
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'CLOSED'))
);

CREATE INDEX idx_tickets_status ON tickets (status);
